nostr:
  privateKey: a21844d65c8696cfcebd4ddce65c8a89a793fbf92986456259606af26cf5ffe6
  relayUrls:
    - wss://relay.nostr.net
    - wss://ithurtswhenip.ee
    - wss://relay.damus.io
    - wss://relay.snort.social
    - wss://relay.nostr.band
mcp:
  name: Plus One Bridge
  about: Adds plus one
  clientName: Plus One Bridge Client
  clientVersion: 1.0.0
  servers:
    - name: Plus One
      command: bun
      args: ["run", "index.ts"]
whitelist:
  allowedPubkeys: []