[package]
name = "{{crate_name}}"
version = "{{version}}"
edition = "2021"
description = "{{description}}"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cassette-tools = { path = "{{cassette_tools_path}}" }
wasm-bindgen = "0.2"
serde_json = "1.0" 