[package]
name = "{{crate_name}}"
version = "{{version}}"
edition = "2021"
description = "{{description}}"

[lib]
crate-type = ["cdylib"]

[dependencies]
cassette-tools = { path = "{{cassette_tools_path}}" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 