[package]
name = "test-nips"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cassette-tools = { path = "../../../cassette-tools", features = ["full"] }
serde_json = "1.0"
chrono = "0.4"